export const mlb = [
  {
    id: 136865,
    date_start: "2023-05-20",
    time_start: "11:10",
    season: "2023",
    home_team: "Chicago White Sox",
    away_team: "Kansas City Royals",
    country: "USA",
    league: "MLB",
    completed: true,
  },
  {
    id: 136857,
    date_start: "2023-05-20",
    time_start: "12:07",
    week: null,
    home_team: "Toronto Blue Jays",
    away_team: "Baltimore Orioles",
    country: "USA",
    league: "MLB",
    completed: true,
  },
  {
    id: 136856,
    date_start: "2023-05-20",
    time_start: "13:05",
    week: null,
    home_team: "San Francisco Giants",
    away_team: "Miami Marlins",
    country: "USA",
    league: "MLB",
    completed: true,
  },
  {
    id: 136858,
    date_start: "2023-05-20",
    time_start: "13:05",
    week: null,
    home_team: "Texas Rangers",
    away_team: "Colorado Rockies",
    country: "USA",
    league: "MLB",
    completed: true,
  },
  {
    id: 136867,
    date_start: "2023-05-20",
    time_start: "13:05",
    week: null,
    home_team: "Philadelphia Phillies",
    away_team: "Chicago Cubs",
    country: "USA",
    league: "MLB",
    completed: true,
  },
  {
    id: 136868,
    date_start: "2023-05-20",
    time_start: "13:05",
    week: null,
    home_team: "Pittsburgh Pirates",
    away_team: "Arizona Diamondbacks",
    country: "USA",
    league: "MLB",
    completed: true,
  },
  {
    id: 136869,
    date_start: "2023-05-20",
    time_start: "13:05",
    week: null,
    home_team: "Washington Nationals",
    away_team: "Detroit Tigers",
    country: "USA",
    league: "MLB",
    completed: true,
  },
  {
    id: 136859,
    date_start: "2023-05-20",
    time_start: "13:10",
    week: null,
    home_team: "Tampa Bay Rays",
    away_team: "Milwaukee Brewers",
    country: "USA",
    league: "MLB",
    completed: true,
  },
  {
    id: 136861,
    date_start: "2023-05-20",
    time_start: "13:10",
    week: null,
    home_team: "Cincinnati Reds",
    away_team: "New York Yankees",
    country: "USA",
    league: "MLB",
    completed: true,
  },
  {
    id: 136864,
    date_start: "2023-05-20",
    time_start: "13:10",
    week: null,
    home_team: "Houston Astros",
    away_team: "Oakland Athletics",
    country: "USA",
    league: "MLB",
    completed: true,
  },
  {
    id: 136860,
    date_start: "2023-05-20",
    time_start: "16:15",
    week: null,
    home_team: "St.Louis Cardinals",
    away_team: "Los Angeles Dodgers",
    country: "USA",
    league: "MLB",
    completed: false,
  },
  {
    id: 136866,
    date: "2023-05-20",
    time: "16:15",
    week: null,
    home_team: "Atlanta Braves",
    away_team: "Seattle Mariners",
    country: "USA",
    league: "MLB",
    completed: true,
  },
  {
    id: 136880,
    date: "2023-05-20",
    time: "19:07",
    week: null,
    home_team: "Los Angeles Angels",
    away_team: "Minnesota Twins",
    country: "USA",
    league: "MLB",
    completed: true,
  },
  {
    id: 136870,
    date: "2023-05-20",
    time: "19:10",
    week: null,
    home_team: "San Diego Padres",
    away_team: "Boston Red Sox",
    country: "USA",
    league: "MLB",
    completed: true,
  }
];