# Generated by Django 4.2.1 on 2023-05-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_baseballgame_start_time_baseballgame_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmericanFootballGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(db_comment='Date football game is slated to start, formatted as YYYY-mm-dd', default='2023-05-21')),
                ('time_start', models.CharField(db_comment='Time baseball game is slated to start, formatted as hh:mm', null=True)),
                ('season', models.CharField(max_length=50, null=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('country', models.CharField(db_comment='The country this game is taking place in', null=True)),
                ('league', models.CharField(null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BasketballGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(db_comment='Date basketball game is slated to start, formatted as YYYY-mm-dd', default='2023-05-21')),
                ('time_start', models.CharField(db_comment='Time baseball game is slated to start, formatted as hh:mm', null=True)),
                ('season', models.CharField(max_length=50, null=True)),
                ('week', models.CharField(null=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('country', models.CharField(db_comment='The country this game is taking place in', null=True)),
                ('league', models.CharField(null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FootballGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(db_comment='Date football game is slated to start, formatted as YYYY-mm-dd', default='2023-05-21')),
                ('time_start', models.CharField(db_comment='Time baseball game is slated to start, formatted as hh:mm', null=True)),
                ('season', models.CharField(max_length=50, null=True)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('country', models.CharField(db_comment='The country this game is taking place in', null=True)),
                ('league', models.CharField(null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='baseballgame',
            name='week',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='date_start',
            field=models.DateTimeField(db_comment='Date baseball game is slated to start, formatted as YYYY-mm-dd', default='2023-05-21'),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='season',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
