# Generated by Django 4.2.1 on 2023-05-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_americanfootballgame_basketballgame_footballgame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballgame',
            name='round',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='footballgame',
            name='time_start',
            field=models.TimeField(db_comment='Time baseball game is slated to start in Timestamp', null=True),
        ),
    ]
