# Generated by Django 4.2.1 on 2023-05-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_footballgame_round_alter_footballgame_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketballgame',
            name='time_start',
            field=models.CharField(db_comment='Time basketball game is slated to start, formatted as hh:mm', null=True),
        ),
        migrations.AlterField(
            model_name='footballgame',
            name='time_start',
            field=models.TimeField(db_comment='Time football game is slated to start in Timestamp', null=True),
        ),
    ]
