# Generated by Django 4.2.1 on 2023-05-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_americanfootballgame_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='americanfootballgame',
            name='time_start',
            field=models.CharField(db_comment='Time football game is slated to start, formatted as hh:mm', null=True),
        ),
    ]
