# Generated by Django 4.2.1 on 2023-05-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_americanfootballgame_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='americanfootballgame',
            name='week',
            field=models.CharField(null=True),
        ),
    ]
