# Generated by Django 4.2.1 on 2023-05-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_gamesmeta_alter_americanfootballgame_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmeta',
            name='league',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='gamesmeta',
            name='sport',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='americanfootballgame',
            name='date_start',
            field=models.DateField(db_comment='Date football game is slated to start, formatted as YYYY-mm-dd', default='2023-05-27'),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='date_start',
            field=models.DateField(db_comment='Date baseball game is slated to start, formatted as YYYY-mm-dd', default='2023-05-27'),
        ),
        migrations.AlterField(
            model_name='basketballgame',
            name='date_start',
            field=models.DateField(db_comment='Date basketball game is slated to start, formatted as YYYY-mm-dd', default='2023-05-27'),
        ),
        migrations.AlterField(
            model_name='footballgame',
            name='date_start',
            field=models.DateField(db_comment='Date football game is slated to start, formatted as YYYY-mm-dd', default='2023-05-27'),
        ),
    ]
