# Generated by Django 4.2.1 on 2023-05-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_gamesmeta_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballgame',
            name='time_start',
            field=models.CharField(db_comment='Time football game is slated to start in Timestamp', null=True),
        ),
    ]
