# Generated by Django 4.2.1 on 2023-06-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_footballgame_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='americanfootballgame',
            name='date_start',
            field=models.DateField(db_comment='Date football game is slated to start, formatted as YYYY-mm-dd', default='2023-06-04'),
        ),
        migrations.AlterField(
            model_name='baseballgame',
            name='date_start',
            field=models.DateField(db_comment='Date baseball game is slated to start, formatted as YYYY-mm-dd', default='2023-06-04'),
        ),
        migrations.AlterField(
            model_name='basketballgame',
            name='date_start',
            field=models.DateField(db_comment='Date basketball game is slated to start, formatted as YYYY-mm-dd', default='2023-06-04'),
        ),
        migrations.AlterField(
            model_name='footballgame',
            name='date_start',
            field=models.DateField(db_comment='Date football game is slated to start, formatted as YYYY-mm-dd', default='2023-06-04'),
        ),
        migrations.AlterField(
            model_name='gamesmeta',
            name='date_updated',
            field=models.DateField(default='2023-06-04'),
        ),
    ]
